language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lcskoerner/react-rest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lcskoerner/react-test npm test -- --coverage

after_success:
  - docker build -t lcskoerner/multi-client ./client
  - docker build -t lcskoerner/multi-nginx ./nginx
  - docker build -t lcskoerner/multi-server ./server
  - docker build -t lcskoerner/multi-worker ./worker
  # Log in to the Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to the Docker Hub
  - docker push lcskoerner/multi-client
  - docker push lcskoerner/multi-nginx
  - docker push lcskoerner/multi-server
  - docker push lcskoerner/multi-worker
